#!/bin/bash
# prev,next
command=$1

title="Now playing"
ncmpcpp $command

text=$(ncmpcpp --now-playing "{%a - %t}|{%f}")
if [[ "$text" ]]; then
    dunstify --timeout=1 --replace 9999 "$title" "$text"
fi
