#!/bin/bash
preset=$1
case $preset in
    'top-left')
        # top left
        x=500
        y=45
        h=330
        w=800
    ;;
    'bottom-left')
        # bottom left
        x=500
        y=410
        h=330
        w=800
    ;;
    'vertical-right')
        # vertical right
        x=60
        y=45
        h=700
        w=400
    ;;
    'small-bottom-left')
        # small bottom left
        x=717
        y=670
        h=80
        w=632
    ;;
    'wide-vertical-left')
        x=500
        y=45
        h=700
        w=800

    ;;
    *)
        echo 'No preset defined'
        exit 1
    ;;
esac
bspc window -t floating=on && xdo move -x $x -y $y && xdo resize -h $h -w $w

