#! /bin/sh
bspc monitor -d 1 2 3 4 5

bspc config border_width        1
bspc config window_gap          10
bspc config bottom_padding      5
bspc config split_ratio         0.52

bspc config borderless_monocle      true
bspc config gapless_monocle         true
#bspc config auto_cancel             true
#bspc config adaptative_raise        true
bspc config focus_follows_pointer   true

~/.config/bspwm/init &
  ~/.config/bspwm/session
