#! /bin/sh
bspc monitor ^1 -d • • • • •
bspc monitor ^2 -d • • • • •

bspc config border_width        1
bspc config window_gap          15
bspc config bottom_padding      0
bspc config split_ratio         0.60

bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config auto_cancel             true
bspc config auto_alternate          true
bspc config adaptative_raise        true
bspc config focus_follows_pointer   true

bspc config rule_command "/home/dario/.config/bspwm/rules %d"

~/.config/bspwm/init &
  ~/.config/bspwm/session
