#!/bin/bash
trap 'jobs -p | xargs kill' EXIT

compton=~/.compton/
dunst=/usr/local/bin/

bspdir=$(dirname $(readlink -f $0))
cd $bspdir

# gnome settings daemon (for fonts and gtk styling)
gnome-settings-daemon &

# set background
# gsettings set org.gnome.desktop.background picture-uri file:///home/user/Pictures/wallpaper.png
feh --bg-tile $bspdir/wallpaper.jpg &

#  gnome-terminal -e ranger &
gnome-terminal &

[[ -e $dunst/dunst ]] \
    && $dunst/dunst -config $bspdir/panels/dunstrc &

# launch compton compositor
#[[ -e $compton/compton ]] \
#  && $compton/compton --config $bspdir/compton.conf &

# launch dzen2 panels
$bspdir/panels/topbar &
    $bspdir/panels/status &

sleep 5 && $bspdir/misc/hide dzen2-bottom-status-bar

wait
