#!/bin/bash
# init script
compton=~/.compton/
bspdir=$(dirname $(readlink -f $0))
cd $bspdir

# gnome settings daemon (for fonts and gtk styling)
gnome-settings-daemon &

# set background
# gsettings set org.gnome.desktop.background picture-uri file:///home/user/Pictures/wallpaper.png
#~/.fehbg &
feh --bg-tile $bspdir/wallpaper.jpg &

# gnome terminals
#gnome-terminal &
#  gnome-terminal -e ranger &

# launch compton compositor
[[ -e $compton/compton ]] \
  && $compton/compton --config $compton/compton.conf &

# launch dzen2 panels
nohup $bspdir/panels/topbar &
    $bspdir/panels/status &
        sleep 5 && $bspdir/misc/hide

