#! /bin/sh
PANEL_HEIGHT=18
FONT_FAMILY='sans-serif'
FONT_SIZE=10
PANEL_FIFO=/tmp/panel-fifo
PANEL_ID=${4:-panel}
INFO_SOURCE=${3:-dzen2}
if [ $(pgrep -cx "$PANEL_ID") -gt 1 ] ; then
    printf "%s\n" "The panel is already running." >&2
    exit 1
fi
trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

flavor=${1:-bar}
position=${2:-top}
case "$position" in
  top)
    position=0
    ;;
  bottom)
    position=750 # screen_height - PANEL_HEIGHT
    ;;
esac

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding $PANEL_HEIGHT
bspc control --subscribe > "$PANEL_FIFO" &

case "$flavor" in
    bar)
        cat "$PANEL_FIFO" | ./panels/bar  &
        ;;
    dzen2)
        . ./panels/colors
        cat "$PANEL_FIFO"\
          | ./panels/$INFO_SOURCE -f "$FONT_FAMILY" -s "$FONT_SIZE"\
          | dzen2 -y $position -h $PANEL_HEIGHT\
              -ta l -fg "$COLOR_FOREGROUND" -bg "$COLOR_BACKGROUND"\
            &
        ;;
esac

wait
