#! /bin/sh
#
# Example panel for dzen2
font_family='lucidasans-8'
font_size=5

. ./panels/colors

adaptive_centering=0
screen_width=1768
center_width=460
center_indent=$(( (screen_width - center_width) / 2 ))
right_indent=$(( (screen_width - 465) ))

NORMIFS=$IFS
FIELDIFS=':'
PADDING=' '

while getopts 'af:s:' opt ; do
    case "$opt" in
        a)
            adaptive_centering=1
            ;;
        f)
            font_family=$OPTARG
            ;;
        s)
            font_size=$OPTARG
            ;;
        w)
            screen_width=$OPTARG
            ;;
    esac
done

shift $((OPTIND - 1))

while read -r line ; do
    case $line in
        W*)
            # bspwm internal state
            wm_infos="$PADDING"
            IFS=$FIELDIFS
            set -- ${line#?}
            while [ $# -gt 0 ] ; do
                item=$1
                case $item in
                    [OoFfUu]*)
                        # desktops
                        name=${item#?}
                        case $item in
                            O*)
                                # focused occupied desktop
                                FG=$COLOR_FOCUSED_OCCUPIED_FG
                                BG=$COLOR_FOCUSED_OCCUPIED_BG
                                ;;
                            F*)
                                # focused free desktop
                                FG=$COLOR_FOCUSED_FREE_FG
                                BG=$COLOR_FOCUSED_FREE_BG
                                ;;
                            U*)
                                # focused urgent desktop
                                FG=$COLOR_FOCUSED_URGENT_FG
                                BG=$COLOR_FOCUSED_URGENT_BG
                                ;;
                            o*)
                                # occupied desktop
                                FG=$COLOR_OCUPPIED_FG
                                BG=$COLOR_OCUPPIED_BG
                                ;;
                            f*)
                                # free desktop
                                FG=$COLOR_FREE_FG
                                BG=$COLOR_FREE_BG
                                ;;
                            u*)
                                # urgent desktop
                                FG=$COLOR_URGENT_FG
                                BG=$COLOR_URGENT_BG
                                ;;
                        esac
                        wm_infos="${wm_infos}^fg(${FG})^bg(${BG})${PADDING}${name}${PADDING}"
                        ;;
                    L*)
                        # layout
                        layout=$(printf "%s" "${item#?}" | sed 's/^\(.\).*/\U\1/')
                        wm_infos="${wm_infos}^fg()^bg()${PADDING}${PADDING}^fg($COLOR_LAYOUT_FG)^bg($COLOR_LAYOUT_BG)"
                        ;;
                esac
                shift
            done
            IFS=$NORMIFS
            ;;
    esac
    mail_dir=~/.mail/private/INBOX/new/
    change=$(stat -c %Y $mail_dir)
    if [ "0$last_change" -eq 0 ]; then
      last_change=$change
    fi
    interval=300
    recent=" "
    if [ $(( $last_change - $change )) -lt $interval ]; then
      recent="*"
    fi
    mail=$(ls -l $mail_dir | wc -l)
    printf "%s\n" "  $wm_infos^pa($center_indent)$(date "+%a %H:%M")^pa($right_indent)$recent $mail ^i(/home/dario/.config/bspwm/panels/dzen/mail.xbm)"
done
