#!/bin/bash
export root=$(dirname $(readlink -f $0))
read screen_width screen_height <<<$(xdpyinfo | grep dimensions | awk '{print $2}' | awk -Fx '{print $1, $2}')
center_indent=$(( ($screen_width / 2) - 30 ))
right_indent=$(( $screen_width - 60 ))

shift $((OPTIND - 1))
while read -r line ; do
    applets='desktop mail clock'
    for applet in $applets; do
        eval "$applet"='$(./panels/applets/$applet $line)'
    done
    printf "%s\n" "   $desktop^pa($center_indent)$clock^pa($right_indent)$mail ^i($HOME/.config/bspwm/icons/mail.xbm)"
done

