#!/bin/bash
line=$@
case $line in
    T*)
        set -- "${line#?}"
        if [[ ${#1} -gt 50 ]]; then
            echo "${1:0:50}..."
        else
            echo $1
        fi
    ;;
    *)
        exit 1
    ;;
esac
